dclient:
	g++ -I./../net -I./../utils -I./../net -I./../timer -I./../net ./../timer/timer.cpp ./../net/CurrentThread.cpp ./../net/EventLoop.cpp ./../net/WrapTCPService.cpp ./../net/DataSocket.cpp ./../net/TCPService.cpp ./../net/SocketLibFunction.c ./../utils/systemlib.c ./../utils/buffer.c BroadCastClient.cpp  -O3 -std=c++0x -lrt -o broadclient
