name: clang-format-lint
on:
  push: {}
  pull_request: {}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: DoozyX/clang-format-lint-action@v0.13
      with:
        ource: '.'
        exclude: './tests'
        extensions: 'h,c,hpp,cc,cpp'
        clangFormatVersion: 11